version: "3.3"

services:
  mysqldb:
    image: mysql
    # restart: always
    # env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  node-docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-mysql-app
    environment:
      NODE_ENV: development      
    networks:
      - web_network
    ports:
      - 3000:3000
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    
networks:
  web_network:
    driver: bridge
    # external: true

volumes: 
  db-config:
  db-data:
